In [25]:
import pandas as pd

df = pd.read_csv("Data/movies_metadata.csv", low_memory=False)

# Ambil kolom penting
df = df[['id','title','overview','genres']]
df = df.dropna(subset=['overview'])
df['overview'] = df['overview'].astype(str)

In [26]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

tfidf = TfidfVectorizer(
    stop_words='english',
    ngram_range=(1,2)
)

tfidf_matrix = tfidf.fit_transform(df['overview'])

In [27]:
def tfidf_search(query, top_k=5):
    query_vec = tfidf.transform([query])
    scores = cosine_similarity(query_vec, tfidf_matrix)[0]
    top_idx = scores.argsort()[::-1][:top_k]
    return df.iloc[top_idx][['title','overview']]

In [28]:
tfidf_search("robot")

                     title                                           overview
28077  Cody the Robosapien  At Kinetech Labs, an inventor named Allan Toph...
32797    OMG, I'm a Robot!         A sensitive guy finds out he's... a robot.
6425    Eve of Destruction  Eve is a military robot made to look exactly l...
4005      Making Mr. Right  A reclusive scientist builds a robot that look...
7161         Robot Stories  Four stories including: "My Robot Baby," in wh...

In [29]:

tfidf_search("love")

,title,overview
43931,A Bela e o Paparazzo,Love on the front page
13513,Nigdy w życiu!,Journey to find true love.
31250,In Lieu of Flowers,Most love stories are about losing love or fin...
36886,Julietta,A dramatic teenage love story set against the ...
36243,"Crouching Tiger, Hidden Dragon: Sword of Destiny","A story of lost love, young love, a legendary ..."

In [30]:
tfidf_search("adventure")

,title,overview
28952,Dinotopia: Quest for the Ruby Sunstone,An Orphaned Boy sets out in search of adventur...
40319,White Wilderness,A fabulous new adventure in exciting entertain...
32819,Pernicious,It was supposed to be an adventure of a lifeti...
34737,Приключения Шерлока Холмса и доктора Ватсона: ...,The Twentieth Century Approaches is a 1986 Sov...
15032,Camille,A twisted honeymoon adventure about a young co...

In [31]:
from rank_bm25 import BM25Okapi

def preprocess(text):
    return text.lower().split()

tokenized_docs = df['overview'].apply(preprocess).tolist()
bm25 = BM25Okapi(tokenized_docs)

In [32]:
def bm25_search(query, top_k=5):
    tokenized_query = preprocess(query)
    scores = bm25.get_scores(tokenized_query)
    top_idx = scores.argsort()[::-1][:top_k]
    return df.iloc[top_idx][['title','overview']]

In [33]:
bm25_search("robot")

                     title                                           overview
28077  Cody the Robosapien  At Kinetech Labs, an inventor named Allan Toph...
6425    Eve of Destruction  Eve is a military robot made to look exactly l...
7161         Robot Stories  Four stories including: "My Robot Baby," in wh...
4005      Making Mr. Right  A reclusive scientist builds a robot that look...
16873               BURN·E  What lengths will a robot undergo to do his jo...

In [34]:
bm25_search("love")

                      title                                           overview
40093           Out of Love  Out of Love encapsulates the sweltering and de...
36886              Julietta  A dramatic teenage love story set against the ...
31250    In Lieu of Flowers  Most love stories are about losing love or fin...
21930  The Thrill of Brazil  Steve, revue producer in Rio de Janeiro, is st...
9161               Dil Se..  The clash between love and ideology is portray...

In [35]:
bm25_search("adventure")

,title,overview
40319,White Wilderness,A fabulous new adventure in exciting entertain...
34737,Приключения Шерлока Холмса и доктора Ватсона: ...,The Twentieth Century Approaches is a 1986 Sov...
25342,Mei and the Kittenbus,Mei has an adventure with a Kittenbus and her ...
32819,Pernicious,It was supposed to be an adventure of a lifeti...
15032,Camille,A twisted honeymoon adventure about a young co...

In [ ]:
from google import genai
import os
from dotenv import load_dotenv
load_dotenv()

client = genai.Client(api_key=os.getenv("GEMINI_API_KEY"))

# fuck you

In [39]:
# get all model
for m in client.models.list():
    print(m.name)

models/gemini-2.5-flash
models/gemini-2.5-pro
models/gemini-2.0-flash
models/gemini-2.0-flash-001
models/gemini-2.0-flash-lite-001
models/gemini-2.0-flash-lite
models/gemini-2.5-flash-preview-tts
models/gemini-2.5-pro-preview-tts
models/gemma-4-26b-a4b-it
models/gemma-4-31b-it
models/gemini-flash-latest
models/gemini-flash-lite-latest
models/gemini-pro-latest
models/gemini-2.5-flash-lite
models/gemini-2.5-flash-image
models/gemini-3-pro-preview
models/gemini-3-flash-preview
models/gemini-3.1-pro-preview
models/gemini-3.1-pro-preview-customtools
models/gemini-3.1-flash-lite-preview
models/gemini-3.1-flash-lite
models/gemini-3-pro-image-preview
models/nano-banana-pro-preview
models/gemini-3.1-flash-image-preview
models/lyria-3-clip-preview
models/lyria-3-pro-preview
models/gemini-3.1-flash-tts-preview
models/gemini-robotics-er-1.5-preview
models/gemini-robotics-er-1.6-preview
models/gemini-2.5-computer-use-preview-10-2025
models/deep-research-max-preview-04-2026
models/deep-research-preview-04-2026
models/deep-research-pro-preview-12-2025
models/gemini-embedding-001
models/gemini-embedding-2-preview
models/gemini-embedding-2
models/aqa
models/imagen-4.0-generate-001
models/imagen-4.0-ultra-generate-001
models/imagen-4.0-fast-generate-001
models/veo-2.0-generate-001
models/veo-3.0-generate-001
models/veo-3.0-fast-generate-001
models/veo-3.1-generate-preview
models/veo-3.1-fast-generate-preview
models/veo-3.1-lite-generate-preview
models/gemini-2.5-flash-native-audio-latest
models/gemini-2.5-flash-native-audio-preview-09-2025
models/gemini-2.5-flash-native-audio-preview-12-2025
models/gemini-3.1-flash-live-preview

In [43]:
from sentence_transformers import SentenceTransformer
from tqdm import tqdm

model = SentenceTransformer('all-MiniLM-L6-v2')

def embed_dataframe_local(df, column, batch_size=128):
    texts = df[column].fillna("").astype(str).tolist()
    embeddings = []

    for i in tqdm(range(0, len(texts), batch_size), desc="Embedding Progress"):
        batch = texts[i:i + batch_size]
        batch_embeddings = model.encode(batch, show_progress_bar=False)
        embeddings.extend(batch_embeddings)

    return embeddings


df['embedding'] = embed_dataframe_local(df, 'overview')

d:\Users\bsi80269\.conda\envs\myenv\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
d:\Users\bsi80269\.conda\envs\myenv\Lib\site-packages\huggingface_hub\file_download.py:138: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in D:\Users\bsi80269\.cache\huggingface\hub\models--sentence-transformers--all-MiniLM-L6-v2. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)
Loading weights: 100%|██████████| 103/103 [00:00<00:00, 4591.78it/s]
Embedding Progress: 100%|██████████| 348/348 [13:29<00:00,  2.33s/it]

In [44]:
df.head()

,id,title,overview,genres,embedding
0,862,Toy Story,"Led by Woody, Andy's toys live happily in his ...","[{'id': 16, 'name': 'Animation'}, {'id': 35, '...","[0.06343902, 0.001026866, 0.09321016, -0.01494..."
1,8844,Jumanji,When siblings Judy and Peter discover an encha...,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...","[0.08630577, 0.0446149, -0.04049633, -0.052532..."
2,15602,Grumpier Old Men,A family wedding reignites the ancient feud be...,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...","[-0.10087597, 0.03744183, -0.00092458416, -0.0..."
3,31357,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...","[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...","[-0.05541904, -0.01451201, 0.031432502, 0.0424..."
4,11862,Father of the Bride Part II,Just when George Banks has recovered from his ...,"[{'id': 35, 'name': 'Comedy'}]","[-0.03138605, -0.0693061, 0.06461947, 0.024486..."

In [ ]:
import chromadb

client = chromadb.Client()
chroma_client = chromadb.Client()
collection = chroma_client.get_collection(name="movies_gemini") if "movies_gemini" in [col.name for col in chroma_client.list_collections()] else chroma_client.create_collection(name="movies_gemini")

In [46]:
# add to collection in chromadb
for idx, row in df.iterrows():
    collection.add(
        ids=[str(row['id'])],
        documents=[row['overview']],
        metadatas=[{"title": row['title']}],
        embeddings=[row['embedding']]
    )

In [47]:
def chroma_search(query, top_k=5):
    query_embedding = model.encode([query])[0]
    results = collection.query(
        query_embeddings=[query_embedding],
        n_results=top_k
    )
    return results['metadatas'][0]

In [48]:
print(chroma_search("Adventure movie with characters named Judy and Peter"))
print(chroma_search("Movies with scenes in New York City"))
print(chroma_search("movie about poet Arthur Rimbaud and Paul Verlaine relationship"))

[{'title': 'Tom and Jerry & The Wizard of Oz'}, {'title': 'Raising Victor Vargas'}, {'title': 'Peter & the Wolf'}, {'title': 'The Wind in the Willows'}, {'title': 'Jumanji'}]
[{'title': 'No More Excuses'}, {'title': 'Kurt Metzger: White Precious'}, {'title': 'Broadway Damage'}, {'title': 'Greenwich Village: Music That Defined a Generation'}, {'title': 'A Most Violent Year'}]
[{'title': 'Total Eclipse'}, {'title': 'Harlan: In the Shadow of Jew Süss'}, {'title': 'Monsieur Verdoux'}, {'title': 'Portrait Werner Herzog'}, {'title': 'Wild Reeds'}]

In [ ]:
import os
from pinecone import Pinecone, ServerlessSpec
load_dotenv()

pc = Pinecone(api_key=os.getenv("PINECONE_API_KEY"))


dimension = len(df['embedding'][0])  # assuming all embeddings have the same dimension

index_name = "movies-geminiv2"
if index_name not in [index.name for index in pc.list_indexes()]:
        pc.create_index(
        name=index_name,
        dimension=dimension,  # match embedding dynamically
        metric="cosine",
        spec=ServerlessSpec(
            cloud="aws",
            region="us-east-1"
        )
    )
index = pc.index(index_name)

In [85]:
# ✅ clean dataset first
df['title'] = df['title'].fillna("Unknown")

batch_size = 128

for i in range(0, len(df), batch_size):
    end = min(i + batch_size, len(df))

    upsert_data = []
    for j in range(i, end):
        upsert_data.append(
            (
                str(df['id'].iloc[j]),
                df['embedding'].iloc[j].tolist(),
                {"title": str(df['title'].iloc[j])}  # ✅ always string
            )
        )

    index.upsert(vectors=upsert_data, namespace="movies")
    
    print(f"Upserted batch {i} to {end}")

print(index.describe_index_stats())


def pinecone_search(query, top_k=5):
    query_emb = model.encode([query])[0]

    result = index.query(
        vector=query_emb.tolist(),  # ✅ ensure list
        top_k=top_k,
        include_metadata=True,
        namespace="movies"
    )

    return result.matches  # ✅ FIX

Upserted batch 0 to 128
Upserted batch 128 to 256
Upserted batch 256 to 384
Upserted batch 384 to 512
Upserted batch 512 to 640
Upserted batch 640 to 768
Upserted batch 768 to 896
Upserted batch 896 to 1024
Upserted batch 1024 to 1152
Upserted batch 1152 to 1280
Upserted batch 1280 to 1408
Upserted batch 1408 to 1536
Upserted batch 1536 to 1664
Upserted batch 1664 to 1792
Upserted batch 1792 to 1920
Upserted batch 1920 to 2048
Upserted batch 2048 to 2176
Upserted batch 2176 to 2304
Upserted batch 2304 to 2432
Upserted batch 2432 to 2560
Upserted batch 2560 to 2688
Upserted batch 2688 to 2816
Upserted batch 2816 to 2944
Upserted batch 2944 to 3072
Upserted batch 3072 to 3200
Upserted batch 3200 to 3328
Upserted batch 3328 to 3456
Upserted batch 3456 to 3584
Upserted batch 3584 to 3712
Upserted batch 3712 to 3840
Upserted batch 3840 to 3968
Upserted batch 3968 to 4096
Upserted batch 4096 to 4224
Upserted batch 4224 to 4352
Upserted batch 4352 to 4480
Upserted batch 4480 to 4608
Upserted batch 4608 to 4736
Upserted batch 4736 to 4864
Upserted batch 4864 to 4992
Upserted batch 4992 to 5120
Upserted batch 5120 to 5248
Upserted batch 5248 to 5376
Upserted batch 5376 to 5504
Upserted batch 5504 to 5632
Upserted batch 5632 to 5760
Upserted batch 5760 to 5888
Upserted batch 5888 to 6016
Upserted batch 6016 to 6144
Upserted batch 6144 to 6272
Upserted batch 6272 to 6400
Upserted batch 6400 to 6528
Upserted batch 6528 to 6656
Upserted batch 6656 to 6784
Upserted batch 6784 to 6912
Upserted batch 6912 to 7040
Upserted batch 7040 to 7168
Upserted batch 7168 to 7296
Upserted batch 7296 to 7424
Upserted batch 7424 to 7552
Upserted batch 7552 to 7680
Upserted batch 7680 to 7808
Upserted batch 7808 to 7936
Upserted batch 7936 to 8064
Upserted batch 8064 to 8192
Upserted batch 8192 to 8320
Upserted batch 8320 to 8448
Upserted batch 8448 to 8576
Upserted batch 8576 to 8704
Upserted batch 8704 to 8832
Upserted batch 8832 to 8960
Upserted batch 8960 to 9088
Upserted batch 9088 to 9216
Upserted batch 9216 to 9344
Upserted batch 9344 to 9472
Upserted batch 9472 to 9600
Upserted batch 9600 to 9728
Upserted batch 9728 to 9856
Upserted batch 9856 to 9984
Upserted batch 9984 to 10112
Upserted batch 10112 to 10240
Upserted batch 10240 to 10368
Upserted batch 10368 to 10496
Upserted batch 10496 to 10624
Upserted batch 10624 to 10752
Upserted batch 10752 to 10880
Upserted batch 10880 to 11008
Upserted batch 11008 to 11136
Upserted batch 11136 to 11264
Upserted batch 11264 to 11392
Upserted batch 11392 to 11520
Upserted batch 11520 to 11648
Upserted batch 11648 to 11776
Upserted batch 11776 to 11904
Upserted batch 11904 to 12032
Upserted batch 12032 to 12160
Upserted batch 12160 to 12288
Upserted batch 12288 to 12416
Upserted batch 12416 to 12544
Upserted batch 12544 to 12672
Upserted batch 12672 to 12800
Upserted batch 12800 to 12928
Upserted batch 12928 to 13056
Upserted batch 13056 to 13184
Upserted batch 13184 to 13312
Upserted batch 13312 to 13440
Upserted batch 13440 to 13568
Upserted batch 13568 to 13696
Upserted batch 13696 to 13824
Upserted batch 13824 to 13952
Upserted batch 13952 to 14080
Upserted batch 14080 to 14208
Upserted batch 14208 to 14336
Upserted batch 14336 to 14464
Upserted batch 14464 to 14592
Upserted batch 14592 to 14720
Upserted batch 14720 to 14848
Upserted batch 14848 to 14976
Upserted batch 14976 to 15104
Upserted batch 15104 to 15232
Upserted batch 15232 to 15360
Upserted batch 15360 to 15488
Upserted batch 15488 to 15616
Upserted batch 15616 to 15744
Upserted batch 15744 to 15872
Upserted batch 15872 to 16000
Upserted batch 16000 to 16128
Upserted batch 16128 to 16256
Upserted batch 16256 to 16384
Upserted batch 16384 to 16512
Upserted batch 16512 to 16640
Upserted batch 16640 to 16768
Upserted batch 16768 to 16896
Upserted batch 16896 to 17024
Upserted batch 17024 to 17152
Upserted batch 17152 to 17280
Upserted batch 17280 to 17408
Upserted batch 17408 to 17536
Upserted batch 17536 to 17664
Upserted batch 17664 to 17792
Upserted batch 17792 to 17920
Upserted batch 17920 to 18048
Upserted batch 18048 to 18176
Upserted batch 18176 to 18304
Upserted batch 18304 to 18432
Upserted batch 18432 to 18560
Upserted batch 18560 to 18688
Upserted batch 18688 to 18816
Upserted batch 18816 to 18944
Upserted batch 18944 to 19072
Upserted batch 19072 to 19200
Upserted batch 19200 to 19328
Upserted batch 19328 to 19456
Upserted batch 19456 to 19584
Upserted batch 19584 to 19712
Upserted batch 19712 to 19840
Upserted batch 19840 to 19968
Upserted batch 19968 to 20096
Upserted batch 20096 to 20224
Upserted batch 20224 to 20352
Upserted batch 20352 to 20480
Upserted batch 20480 to 20608
Upserted batch 20608 to 20736
Upserted batch 20736 to 20864
Upserted batch 20864 to 20992
Upserted batch 20992 to 21120
Upserted batch 21120 to 21248
Upserted batch 21248 to 21376
Upserted batch 21376 to 21504
Upserted batch 21504 to 21632
Upserted batch 21632 to 21760
Upserted batch 21760 to 21888
Upserted batch 21888 to 22016
Upserted batch 22016 to 22144
Upserted batch 22144 to 22272
Upserted batch 22272 to 22400
Upserted batch 22400 to 22528
Upserted batch 22528 to 22656
Upserted batch 22656 to 22784
Upserted batch 22784 to 22912
Upserted batch 22912 to 23040
Upserted batch 23040 to 23168
Upserted batch 23168 to 23296
Upserted batch 23296 to 23424
Upserted batch 23424 to 23552
Upserted batch 23552 to 23680
Upserted batch 23680 to 23808
Upserted batch 23808 to 23936
Upserted batch 23936 to 24064
Upserted batch 24064 to 24192
Upserted batch 24192 to 24320
Upserted batch 24320 to 24448
Upserted batch 24448 to 24576
Upserted batch 24576 to 24704
Upserted batch 24704 to 24832
Upserted batch 24832 to 24960
Upserted batch 24960 to 25088
Upserted batch 25088 to 25216
Upserted batch 25216 to 25344
Upserted batch 25344 to 25472
Upserted batch 25472 to 25600
Upserted batch 25600 to 25728
Upserted batch 25728 to 25856
Upserted batch 25856 to 25984
Upserted batch 25984 to 26112
Upserted batch 26112 to 26240
Upserted batch 26240 to 26368
Upserted batch 26368 to 26496
Upserted batch 26496 to 26624
Upserted batch 26624 to 26752
Upserted batch 26752 to 26880
Upserted batch 26880 to 27008
Upserted batch 27008 to 27136
Upserted batch 27136 to 27264
Upserted batch 27264 to 27392
Upserted batch 27392 to 27520
Upserted batch 27520 to 27648
Upserted batch 27648 to 27776
Upserted batch 27776 to 27904
Upserted batch 27904 to 28032
Upserted batch 28032 to 28160
Upserted batch 28160 to 28288
Upserted batch 28288 to 28416
Upserted batch 28416 to 28544
Upserted batch 28544 to 28672
Upserted batch 28672 to 28800
Upserted batch 28800 to 28928
Upserted batch 28928 to 29056
Upserted batch 29056 to 29184
Upserted batch 29184 to 29312
Upserted batch 29312 to 29440
Upserted batch 29440 to 29568
Upserted batch 29568 to 29696
Upserted batch 29696 to 29824
Upserted batch 29824 to 29952
Upserted batch 29952 to 30080
Upserted batch 30080 to 30208
Upserted batch 30208 to 30336
Upserted batch 30336 to 30464
Upserted batch 30464 to 30592
Upserted batch 30592 to 30720
Upserted batch 30720 to 30848
Upserted batch 30848 to 30976
Upserted batch 30976 to 31104
Upserted batch 31104 to 31232
Upserted batch 31232 to 31360
Upserted batch 31360 to 31488
Upserted batch 31488 to 31616
Upserted batch 31616 to 31744
Upserted batch 31744 to 31872
Upserted batch 31872 to 32000
Upserted batch 32000 to 32128
Upserted batch 32128 to 32256
Upserted batch 32256 to 32384
Upserted batch 32384 to 32512
Upserted batch 32512 to 32640
Upserted batch 32640 to 32768
Upserted batch 32768 to 32896
Upserted batch 32896 to 33024
Upserted batch 33024 to 33152
Upserted batch 33152 to 33280
Upserted batch 33280 to 33408
Upserted batch 33408 to 33536
Upserted batch 33536 to 33664
Upserted batch 33664 to 33792
Upserted batch 33792 to 33920
Upserted batch 33920 to 34048
Upserted batch 34048 to 34176
Upserted batch 34176 to 34304
Upserted batch 34304 to 34432
Upserted batch 34432 to 34560
Upserted batch 34560 to 34688
Upserted batch 34688 to 34816
Upserted batch 34816 to 34944
Upserted batch 34944 to 35072
Upserted batch 35072 to 35200
Upserted batch 35200 to 35328
Upserted batch 35328 to 35456
Upserted batch 35456 to 35584
Upserted batch 35584 to 35712
Upserted batch 35712 to 35840
Upserted batch 35840 to 35968
Upserted batch 35968 to 36096
Upserted batch 36096 to 36224
Upserted batch 36224 to 36352
Upserted batch 36352 to 36480
Upserted batch 36480 to 36608
Upserted batch 36608 to 36736
Upserted batch 36736 to 36864
Upserted batch 36864 to 36992
Upserted batch 36992 to 37120
Upserted batch 37120 to 37248
Upserted batch 37248 to 37376
Upserted batch 37376 to 37504
Upserted batch 37504 to 37632
Upserted batch 37632 to 37760
Upserted batch 37760 to 37888
Upserted batch 37888 to 38016
Upserted batch 38016 to 38144
Upserted batch 38144 to 38272
Upserted batch 38272 to 38400
Upserted batch 38400 to 38528
Upserted batch 38528 to 38656
Upserted batch 38656 to 38784
Upserted batch 38784 to 38912
Upserted batch 38912 to 39040
Upserted batch 39040 to 39168
Upserted batch 39168 to 39296
Upserted batch 39296 to 39424
Upserted batch 39424 to 39552
Upserted batch 39552 to 39680
Upserted batch 39680 to 39808
Upserted batch 39808 to 39936
Upserted batch 39936 to 40064
Upserted batch 40064 to 40192
Upserted batch 40192 to 40320
Upserted batch 40320 to 40448
Upserted batch 40448 to 40576
Upserted batch 40576 to 40704
Upserted batch 40704 to 40832
Upserted batch 40832 to 40960
Upserted batch 40960 to 41088
Upserted batch 41088 to 41216
Upserted batch 41216 to 41344
Upserted batch 41344 to 41472
Upserted batch 41472 to 41600
Upserted batch 41600 to 41728
Upserted batch 41728 to 41856
Upserted batch 41856 to 41984
Upserted batch 41984 to 42112
Upserted batch 42112 to 42240
Upserted batch 42240 to 42368
Upserted batch 42368 to 42496
Upserted batch 42496 to 42624
Upserted batch 42624 to 42752
Upserted batch 42752 to 42880
Upserted batch 42880 to 43008
Upserted batch 43008 to 43136
Upserted batch 43136 to 43264
Upserted batch 43264 to 43392
Upserted batch 43392 to 43520
Upserted batch 43520 to 43648
Upserted batch 43648 to 43776
Upserted batch 43776 to 43904
Upserted batch 43904 to 44032
Upserted batch 44032 to 44160
Upserted batch 44160 to 44288
Upserted batch 44288 to 44416
Upserted batch 44416 to 44512
DescribeIndexStatsResponse(dimension=384, total_vector_count=44482, metric='cosine', namespaces=1)

In [86]:
print(pinecone_search("Adventure movie with characters named Judy and Peter"))
print(pinecone_search("Movies with scenes in New York City"))
print(pinecone_search("movie about poet Arthur Rimbaud and Paul Verlaine relationship"))

[ScoredVector(id='72972', score=0.515211165, values=[], metadata={'title': 'Tom and Jerry & The Wizard of Oz'}), ScoredVector(id='25461', score=0.507881224, values=[], metadata={'title': 'Raising Victor Vargas'}), ScoredVector(id='14518', score=0.505898476, values=[], metadata={'title': 'Peter & the Wolf'}), ScoredVector(id='59178', score=0.496110946, values=[], metadata={'title': 'The Wind in the Willows'}), ScoredVector(id='8844', score=0.489058495, values=[], metadata={'title': 'Jumanji'})]
[ScoredVector(id='110692', score=0.618826866, values=[], metadata={'title': 'No More Excuses'}), ScoredVector(id='281590', score=0.612108231, values=[], metadata={'title': 'Kurt Metzger: White Precious'}), ScoredVector(id='41638', score=0.583842337, values=[], metadata={'title': 'Broadway Damage'}), ScoredVector(id='158232', score=0.578264236, values=[], metadata={'title': 'Greenwich Village: Music That Defined a Generation'}), ScoredVector(id='241239', score=0.571762085, values=[], metadata={'title': 'A Most Violent Year'})]
[ScoredVector(id='36834', score=0.738124847, values=[], metadata={'title': 'Total Eclipse'}), ScoredVector(id='89126', score=0.510739386, values=[], metadata={'title': 'Harlan: In the Shadow of Jew Süss'}), ScoredVector(id='30588', score=0.499808311, values=[], metadata={'title': 'Monsieur Verdoux'}), ScoredVector(id='162451', score=0.475672722, values=[], metadata={'title': 'Portrait Werner Herzog'}), ScoredVector(id='26933', score=0.475291252, values=[], metadata={'title': 'Wild Reeds'})]